### ISSUE TITLE
History table should be populated from the databses when the the Project is run

### ISSUE THREAD

**Issue by hussainashiqktk** [hussainashiqktk/linkSqueezer#5]
![image](https://github.com/hussainashiqktk/linkSqueezer/assets/74835399/a59e9d53-0104-465f-b9cf-cd9d34420b13)

This table should be populated from the datbase file DB.csv if there are some entries inside it.

**Comment by UzairURK** [comment]
@hussainashiqktk assign this issue to me

**Comment by hussainashiqktk** [comment]
can you provide a screenshot?

**Comment by UzairURK** [comment]
![Screenshot (83)](https://github.com/hussainashiqktk/linkSqueezer/assets/82904313/739b5d87-ce9a-4944-a3d1-11b991fa7228)
